apiVersion: v1
entries:
  minio:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2023.4.28
    created: "2023-09-12T11:39:53.656657-04:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
      storage service, mainly used for storing unstructured data (such as photos,
      videos, log files, etc.).
    digest: 062714264aa6bf4d169ca094ea50d027e7ec8e208815010fc9361ace44f4105d
    home: https://github.com/bitnami/charts/tree/main/bitnami/minio
    icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: minio
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/minio
    - https://min.io
    urls:
    - charts/minio-12.4.2.tgz
    version: 12.4.2
  postgresql:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 15.2.0
    created: "2023-09-12T11:39:53.663187-04:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 5a7b6e07333363c04fd8adb6a5bea1f9c1ad4646fb82dee32417f04374b8d7d3
    home: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-12.3.1.tgz
    version: 12.3.1
  windmill:
  - apiVersion: v2
    appVersion: 1.139.0
    created: "2023-09-12T11:39:53.653148-04:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.3.1
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 12.4.2
    description: Windmill - Turn scripts into endpoints, workflows and UIs in minutes
    digest: 215179f877e89082c2e46a58e70d0d182f58d5e5aed568c8babd8c4a45d2ec1c
    home: https://www.windmill.dev/
    icon: https://www.windmill.dev/img/windmill.svg
    keywords:
    - windmill
    - scripts
    - flows
    - workflows
    - internal
    - apps
    - open-source
    maintainers:
    - email: ruben@windmill.dev
      name: windmill
      url: https://www.windmill.dev/
    name: windmill
    sources:
    - https://github.com/isc-patrick/windmill-svc.git
    type: application
    urls:
    - windmill-1.6.51.tgz
    version: 1.6.51
generated: "2023-09-12T11:39:53.639601-04:00"
